name: Lunar Tech github workflow

on:
  workflow_dispatch:
    
  push:
    branches:
      - main

jobs:
  buil-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run hello
        run: echo 'hello world'
      - name: show system username
        run: uname -a
      - name: Show current date
        run: date